### ISSUE TITLE
@mgcrea/fastify-session should be a peerDependency, not a devDependency

### ISSUE THREAD

**Issue by utrolig** [mgcrea/fastify-session-sodium-crypto#2]
As the title states, @mgcrea/fastify-session should be a peerDependency, not a devDependency.

When I run `pnpm prune --prod` to clean up my Docker image, my application is not able to resolve `@mgcrea/fastify-session` from `@mgcrea/fastify-session-sodium-crypto`

**Comment by mgcrea** [comment]
Thanks for the PR!

Just released [v0.8.6](https://github.com/mgcrea/fastify-session-sodium-crypto/releases/tag/v0.8.6) with the fix.

**Comment by utrolig** [comment]
Thank you!
